import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  pt: {
    // Nav
    nav_collections: 'Coleções',
    nav_mansion: 'A Mansão',
    nav_login: 'Entrar',
    nav_profile: 'Perfil',
    nav_logout: 'Sair',
    // Hero
    hero_title: 'O SABOR DA FESTA.',
    hero_subtitle: '0% ESTIMULANTES.',
    hero_vibe: '100% VIBE.',
    hero_desc: 'Projete seu shape sem o caos cardíaco. O Goró é o combustível inexplicável para quem busca performance e redução de danos.',
    hero_cta: 'Projetar Agora',
    // Home Sections
    home_voices_title: 'Vozes da Mansão',
    home_voice1_text: 'O único drink que me permite performar no palco e na academia sem o crash do café.',
    home_voice2_text: 'Redução de danos nunca foi tão sexy. O shape agradece e a mente flutua.',
    home_voice3_text: 'Substituí o álcool por Goró e minha criatividade triplicou. Mansão lifestyle.',
    home_science_badge: 'Por que o Goró?',
    home_science_title: 'A Ciência do Shape Inexplicável',
    home_science_desc: 'Esqueça o colapso. Desenvolvemos a alquimia perfeita para quem vive no limite entre a performance do dia e o caos da noite.',
    home_danger_badge: 'O Perigo',
    home_danger_title: 'Energético Comum + Álcool = Caos Cardíaco',
    home_danger_h1: 'Taquicardia Descontrolada',
    home_danger_p1: 'O excesso de cafeína sintética mascara a embriaguez e sobrecarrega o miocárdio em tempo recorde.',
    home_danger_h2: 'Ansiedade & Queda',
    home_danger_p2: 'O pico de açúcar seguido pela queda brusca gera irritabilidade e uma "bad trip" garantida no dia seguinte.',
    home_danger_h3: 'Burnout Celular',
    home_danger_p3: 'Estresse oxidativo agressivo que drena sua energia vital e destrói sua recuperação muscular.',
    home_rev_badge: 'A Revolução',
    home_rev_title: 'Goró da Mansão = Vibe Pura & Redução de Danos',
    home_rev_h1: 'Hidratação Inteligente',
    home_rev_p1: 'Eletrólitos biodisponíveis que mantêm o equilíbrio osmótico mesmo sob o efeito do álcool.',
    home_rev_h2: 'Foco & Vitaminas',
    home_rev_p2: 'Complexo B e Nootrópicos naturais que protegem o fígado e mantêm a mente afiada na pista.',
    home_rev_h3: 'Sem Ressaca Atômica',
    home_rev_p3: 'Curadoria de ervas adaptógenas que suavizam a descida, garantindo um despertar sem arrependimentos.',
    // Catalog
    cat_title: 'Catálogo Sensorial',
    cat_desc: 'Sabor Energético Original. Inexplicável. Uma curadoria de vibrações líquidas destiladas para a elite do caos.',
    add_to_cart: 'Adicionar ao Carrinho',
    // Checkout
    checkout_title: 'Sua Seleção',
    checkout_empty: 'Seu carrinho está vazio',
    checkout_subtotal: 'Subtotal',
    checkout_shipping: 'Frete',
    checkout_shipping_free: 'Cortesia',
    checkout_total: 'Total',
    checkout_delivery: 'Entrega',
    checkout_payment: 'Pagamento',
    checkout_new_card: 'Novo Cartão',
    checkout_save_card: 'Salvar este cartão para compras futuras',
    checkout_finalize: 'Finalizar Pedido',
    checkout_processing: 'Sincronizando Alquimia...',
    checkout_card_holder: 'Nome no Cartão',
    checkout_card_number: 'Número do Cartão',
    checkout_expiry: 'MM/AA',
    checkout_cvv: 'CVV',
    // Profile
    profile_title: 'Membro Mansão',
    profile_tab_info: 'Perfil',
    profile_tab_orders: 'Pedidos',
    profile_tab_addr: 'Endereços',
    profile_tab_pay: 'Pagamentos',
    profile_save: 'Salvar Alterações',
    profile_save_success: 'Perfil Sincronizado',
    profile_name_label: 'Nome Completo',
    profile_email_label: 'Endereço de E-mail',
    order_id: 'ID do Pedido',
    order_total: 'Total Pago',
    order_empty: 'Nenhum pedido realizado',
    addr_saved: 'Endereços Salvos',
    addr_new: 'Adicionar Novo',
    addr_street: 'Rua / Logradouro',
    addr_city: 'Cidade',
    addr_state: 'Estado',
    addr_zip: 'CEP',
    addr_save: 'Salvar Endereço',
    addr_cancel: 'Cancelar',
    pay_methods: 'Métodos de Pagamento',
    pay_new: 'Novo Cartão',
    pay_holder: 'Nome do Titular',
    pay_number: 'Número do Cartão',
    pay_expiry: 'Validade',
    pay_save: 'Salvar Cartão',
    // Auth
    login_title: 'Entrar',
    login_subtitle: 'Acesse a Mansão',
    login_email: 'E-mail',
    login_pass: 'Senha',
    login_btn: 'Entrar no Vazio',
    login_no_acc: 'Ainda não tem convite?',
    login_register_link: 'Solicitar Acesso',
    reg_title: 'Novo Membro',
    reg_subtitle: 'Solicite seu acesso à Mansão',
    reg_name: 'Nome Completo',
    reg_email: 'E-mail',
    reg_pass: 'Senha',
    reg_btn: 'Obter Acesso',
    reg_has_acc: 'Já é da Mansão?',
    reg_login_link: 'Fazer Login',
    auth_err_creds: 'Credenciais inválidas',
    auth_err_conn: 'Erro de conexão',
    auth_err_reg: 'Erro ao criar conta',
    // Footer
    footer_desc: 'A elite do caos merece o sabor da perfeição. Sem estimulantes, apenas a vibe pura da Mansão.',
    footer_shop: 'Loja',
    footer_support: 'Suporte',
    footer_terms: 'Termos',
    footer_privacy: 'Privacidade',
    footer_rights: 'Todos os direitos reservados.',
    // Misc
    loading: 'CARREGANDO_SESSÃO...',
    success_title: 'Pedido Confirmado',
    success_desc: 'Sua jornada sensorial começou. Prepare-se para elevar sua experiência ao nível Mansão.',
    success_cta: 'Ver meus pedidos',
    back_to_catalog: 'Retornar ao Catálogo',
    back_to_shop: 'Voltar às Compras',
    // Admin
    admin_title: 'Painel de Controle',
    admin_add_prod: 'Adicionar Produto',
    admin_prod_name: 'Nome do Produto',
    admin_prod_flavor: 'Sabor Principal',
    admin_prod_tag: 'Tag (ex: Vibe)',
    admin_prod_price: 'Preço (ex: 249,00)',
    admin_prod_desc: 'Descrição Detalhada',
    admin_prod_img: 'URL da Imagem',
    admin_prod_color: 'Cor (primary, secondary, etc)',
    admin_prod_btn: 'Distilar Produto',
    admin_prod_success: 'Alquimia concluída! Produto adicionado.',
    // Products
    p_neon_lime_name: 'Neon Lime',
    p_neon_lime_desc: 'O sabor da festa. Complexo vitamínico B, 0% Cafeína. A explosão cítrica que corta o escuro.',
    p_pink_void_name: 'Pink Void',
    p_pink_void_desc: 'Mais profundo que o desejo. Complexo vitamínico B, 0% Cafeína. O toque aveludado das sombras.',
    p_cyan_freeze_name: 'Cyan Freeze',
    p_cyan_freeze_desc: 'Zero Absoluto. Complexo vitamínico B, 0% Cafeína. O frio cortante da madrugada urbana.',
    p_yellow_pulse_name: 'Yellow Pulse',
    p_yellow_pulse_desc: 'Energia Pura. Complexo vitamínico B, 0% Cafeína. O calor magnético que não deixa parar.',
    p_purple_haze_name: 'Purple Haze',
    p_purple_haze_desc: 'Mente Elétrica. À base de Nootrópicos, 0% Álcool. A sintonia fina entre o corpo e a alma.',
    p_emerald_night_name: 'Emerald Night',
    p_emerald_night_desc: 'Calma Focada. Enriquecido com L-Teanina. O silêncio absoluto no meio do festival.'
  },
  en: {
    // Nav
    nav_collections: 'Collections',
    nav_mansion: 'The Mansion',
    nav_login: 'Log In',
    nav_profile: 'Profile',
    nav_logout: 'Logout',
    // Hero
    hero_title: 'THE FLAVOR OF THE PARTY.',
    hero_subtitle: '0% STIMULANTS.',
    hero_vibe: '100% VIBE.',
    hero_desc: 'Design your shape without cardiac chaos. Goró is the inexplicable fuel for those seeking performance and harm reduction.',
    hero_cta: 'Design Now',
    // Home Sections
    home_voices_title: 'Mansion Voices',
    home_voice1_text: 'The only drink that lets me perform on stage and in the gym without the coffee crash.',
    home_voice2_text: 'Harm reduction has never been so sexy. The shape thanks you and the mind floats.',
    home_voice3_text: 'I replaced alcohol with Goró and my creativity tripled. Mansion lifestyle.',
    home_science_badge: 'Why Goró?',
    home_science_title: 'The Science of the Inexplicable Shape',
    home_science_desc: 'Forget the collapse. We developed the perfect alchemy for those living on the edge between daytime performance and nighttime chaos.',
    home_danger_badge: 'The Danger',
    home_danger_title: 'Common Energy Drink + Alcohol = Cardiac Chaos',
    home_danger_h1: 'Uncontrolled Tachycardia',
    home_danger_p1: 'Excess synthetic caffeine masks drunkenness and overloads the myocardium in record time.',
    home_danger_h2: 'Anxiety & Crash',
    home_danger_p2: 'The sugar peak followed by a sharp drop generates irritability and a guaranteed "bad trip" the next day.',
    home_danger_h3: 'Cellular Burnout',
    home_danger_p3: 'Aggressive oxidative stress that drains your vital energy and destroys your muscle recovery.',
    home_rev_badge: 'The Revolution',
    home_rev_title: 'Mansion Goró = Pure Vibe & Harm Reduction',
    home_rev_h1: 'Smart Hydration',
    home_rev_p1: 'Bioavailable electrolytes that maintain osmotic balance even under the effect of alcohol.',
    home_rev_h2: 'Focus & Vitamins',
    home_rev_p2: 'Vitamin B complex and natural Nootropics that protect the liver and keep the mind sharp on the floor.',
    home_rev_h3: 'No Atomic Hangover',
    home_rev_p3: 'Curation of adaptogenic herbs that soften the descent, ensuring a regret-free awakening.',
    // Catalog
    cat_title: 'Sensory Catalog',
    cat_desc: 'Original Energetic Flavor. Inexplicable. A curation of liquid vibrations distilled for the elite of chaos.',
    add_to_cart: 'Add to Cart',
    // Checkout
    checkout_title: 'Your Selection',
    checkout_empty: 'Your cart is empty',
    checkout_subtotal: 'Subtotal',
    checkout_shipping: 'Shipping',
    checkout_shipping_free: 'Complimentary',
    checkout_total: 'Total',
    checkout_delivery: 'Delivery',
    checkout_payment: 'Payment',
    checkout_new_card: 'New Card',
    checkout_save_card: 'Save this card for future purchases',
    checkout_finalize: 'Finalize Order',
    checkout_processing: 'Syncing Alchemy...',
    checkout_card_holder: 'Card Holder Name',
    checkout_card_number: 'Card Number',
    checkout_expiry: 'MM/YY',
    checkout_cvv: 'CVV',
    // Profile
    profile_title: 'Mansion Member',
    profile_tab_info: 'Profile',
    profile_tab_orders: 'Orders',
    profile_tab_addr: 'Addresses',
    profile_tab_pay: 'Payments',
    profile_save: 'Save Changes',
    profile_save_success: 'Profile Synced',
    profile_name_label: 'Full Name',
    profile_email_label: 'Email Address',
    order_id: 'Order ID',
    order_total: 'Total Paid',
    order_empty: 'No orders yet',
    addr_saved: 'Saved Locations',
    addr_new: 'Add New',
    addr_street: 'Street Address',
    addr_city: 'City',
    addr_state: 'State',
    addr_zip: 'ZIP Code',
    addr_save: 'Save Address',
    addr_cancel: 'Cancel',
    pay_methods: 'Payment Methods',
    pay_new: 'New Card',
    pay_holder: 'Holder Name',
    pay_number: 'Card Number',
    pay_expiry: 'Expiry Date',
    pay_save: 'Save Card',
    // Auth
    login_title: 'Log In',
    login_subtitle: 'Access the Mansion',
    login_email: 'Email',
    login_pass: 'Password',
    login_btn: 'Enter the Void',
    login_no_acc: 'No invite yet?',
    login_register_link: 'Request Access',
    reg_title: 'New Member',
    reg_subtitle: 'Request your Mansion access',
    reg_name: 'Full Name',
    reg_email: 'Email',
    reg_pass: 'Password',
    reg_btn: 'Get Access',
    reg_has_acc: 'Already from the Mansion?',
    reg_login_link: 'Log In',
    auth_err_creds: 'Invalid credentials',
    auth_err_conn: 'Connection error',
    auth_err_reg: 'Error creating account',
    // Footer
    footer_desc: 'The elite of chaos deserve the taste of perfection. No stimulants, just the pure Mansion vibe.',
    footer_shop: 'Shop',
    footer_support: 'Support',
    footer_terms: 'Terms',
    footer_privacy: 'Privacy',
    footer_rights: 'All rights reserved.',
    // Misc
    loading: 'LOADING_SESSION...',
    success_title: 'Order Confirmed',
    success_desc: 'Your sensory journey has begun. Prepare to elevate your experience to the Mansion level.',
    success_cta: 'View my orders',
    back_to_catalog: 'Back to Catalog',
    back_to_shop: 'Back to Shop',
    // Admin
    admin_title: 'Control Panel',
    admin_add_prod: 'Add Product',
    admin_prod_name: 'Product Name',
    admin_prod_flavor: 'Main Flavor',
    admin_prod_tag: 'Tag (e.g., Vibe)',
    admin_prod_price: 'Price (e.g., 249.00)',
    admin_prod_desc: 'Detailed Description',
    admin_prod_img: 'Image URL',
    admin_prod_color: 'Color (primary, secondary, etc)',
    admin_prod_btn: 'Distill Product',
    admin_prod_success: 'Alchemy complete! Product added.',
    // Products
    p_neon_lime_name: 'Neon Lime',
    p_neon_lime_desc: 'The flavor of the party. Vitamin B complex, 0% Caffeine. The citrus explosion that cuts through the dark.',
    p_pink_void_name: 'Pink Void',
    p_pink_void_desc: 'Deeper than desire. Vitamin B complex, 0% Caffeine. The velvety touch of shadows.',
    p_cyan_freeze_name: 'Cyan Freeze',
    p_cyan_freeze_desc: 'Absolute Zero. Vitamin B complex, 0% Caffeine. The biting cold of the urban dawn.',
    p_yellow_pulse_name: 'Yellow Pulse',
    p_yellow_pulse_desc: 'Pure Energy. Vitamin B complex, 0% Caffeine. The magnetic heat that never stops.',
    p_purple_haze_name: 'Purple Haze',
    p_purple_haze_desc: 'Electric Mind. Nootropics-based, 0% Alcohol. The fine tuning between body and soul.',
    p_emerald_night_name: 'Emerald Night',
    p_emerald_night_desc: 'Focused Calm. Enriched with L-Theanine. Absolute silence in the middle of the festival.'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'pt');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
